dist: trusty

language: python

python:
 - 2.7
 - 2.6

sudo: false

addons:
  apt:
    packages:
    - rtmpdump
    - python-crypto
    - php5-cli
    - php5-curl

install:
 - pip install pyflakes pep8
 - python setup.py install

script:
 - pyflakes yledl/yledl.py
 - python setup.py pytest
 - yle-dl --help

after_script:
 - pep8 --statistics --count yledl/yledl.py
